name: Security Checks
on:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    - cron: "0 17 * * *"
jobs:
  Security-Scan:
    uses: razorpay/security-action/.github/workflows/central_security_checks_prod.yml@master
    with:
      SEMGREP_MANDATORY: "true"
    secrets: inherit