name: Security
on:
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    - cron: "30 20 * * *"
jobs:
  security-sast:
    uses: razorpay/security-action/.github/workflows/semgrep.yml@master
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
