name: Security
on:
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:
  pull_request: {}
  push:
    branches: ["master"]
  schedule:
    - cron: "30 20 * * *"
jobs:
  security-sast:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "TODO!"

  security-statuscheck:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "TODO!"
